# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-06 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='详细新闻名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=60, verbose_name='新闻专题')),
                ('desc', models.CharField(max_length=300, verbose_name='新闻描述')),
                ('detail', models.TextField(verbose_name='新闻详情')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('category', models.CharField(choices=[('ss', '时事'), ('dj', '财经'), ('gj', '国际')], max_length=2, verbose_name='新闻类别')),
                ('user_nums', models.IntegerField(default=0, verbose_name='观看人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图片')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='新闻标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('news_annoucements', models.CharField(default='', max_length=500, verbose_name='公告')),
                ('youneedknow', models.CharField(default='', max_length=300, verbose_name='须知')),
                ('news_tell', models.CharField(default='', max_length=300, verbose_name='我们告诉你')),
            ],
            options={
                'verbose_name': '新闻专题',
                'verbose_name_plural': '新闻专题',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('url', models.CharField(default='', max_length=200, verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('watchtime', models.IntegerField(default=0, verbose_name='观看时长（分钟数）')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='详细新闻')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsTopic', verbose_name='新闻'),
        ),
    ]
