# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNews',
            new_name='UserNewsTopic',
        ),
        migrations.AlterField(
            model_name='usernewstopic',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsTopic', verbose_name='新闻'),
        ),
    ]
